name: beyond_peaks
description: BeyondPeaks stage one app shell.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  go_router: ^17.2.3
  three_js: ^0.2.7

dependency_overrides:
  flutter_angle:
    path: third_party/flutter_angle

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/textures/planets/
